version: '3.8'

services:
  nginx:
    build: ./nginx
    command: nginx -g 'daemon off;'
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./.env.dev

  web: 
    build: ./app
    command: gunicorn --bind 0.0.0.0 --workers=3 tammy.wsgi
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev